In [2]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym

# Eigenvalues and Eigenvectors


In [3]:
# create a coefficient matrix
A = np.array([[-2, -4, 2], [-2, 1, 2], [4, 2, 5]])

As = sym.Matrix([[-2, -4, 2], [-2, 1, 2], [4, 2, 5]])

In [4]:
As

Matrix([
[-2, -4, 2],
[-2,  1, 2],
[ 4,  2, 5]])

# Eigenvalues and Eigenvectors

Consider a square matrix $A$ of size $n \times n$. If there exists a vector $x$ of size $n \times 1$ and a scalar $\lambda$ such that

$$Ax = \lambda x$$

then $\lambda$ is called an eigenvalue of $A$ and $x$ is called an eigenvector of $A$ corresponding to the eigenvalue $\lambda$.

The eigenvalues of a matrix $A$ are the roots of the characteristic equation

$$det(A - \lambda I) = 0$$

where $I$ is the identity matrix of size $n \times n$.

The eigenvectors of a matrix $A$ are the vectors $x$ that satisfy the equation

$$(A - \lambda I)x = 0$$

for some eigenvalue $\lambda$.

The eigenvalues and eigenvectors of a matrix $A$ can be calculated using the `eig` function of the `numpy.linalg` module.

In [5]:
# print the eigenvalues and eigenvectors of the coefficient matrix
eigenvalues, eigenvectorsT = np.linalg.eig(A)
eigenvectors = eigenvectorsT.T
print('The eigenvalues are ')
print(eigenvalues)
print('The eigenvectors (rows) are ')
print(eigenvectors)
print()

The eigenvalues are 
[-5.  3.  6.]
The eigenvectors (rows) are 
[[ 0.81649658  0.40824829 -0.40824829]
 [ 0.53452248 -0.80178373 -0.26726124]
 [ 0.05842062  0.35052374  0.93472998]]



## Direct Calculation of Eigenvalues and Eigenvectors using Sympy

In [8]:
lam = sym.symbols('lambda')
lambda_matrix = sym.Matrix([[lam, 0, 0], [0, lam, 0], [0, 0, lam]])
print('The lambda matrix is ')
lambda_matrix

The lambda matrix is 


Matrix([
[lambda,      0,      0],
[     0, lambda,      0],
[     0,      0, lambda]])

In [9]:
eigen_matrix = As - lambda_matrix
print('The eigen matrix is ')
eigen_matrix

The eigen matrix is 


Matrix([
[-lambda - 2,         -4,          2],
[         -2, 1 - lambda,          2],
[          4,          2, 5 - lambda]])

In [10]:
det = eigen_matrix.det()
print('The determinant is ')
det

The determinant is 


-lambda**3 + 4*lambda**2 + 27*lambda - 90

In [11]:
eigenvalues = sym.solve(det)
print('The eigenvalues are ')
print(eigenvalues)

The eigenvalues are 
[-5, 3, 6]


In [9]:
# calculate the eigenvectors ... note that the result is a DICTIONARY

In [12]:
eigenvectors = []
for eigenvalue in eigenvalues:
    print('For eigenvalue ',eigenvalue,' the eigenvectors are ')
    print(eigen_matrix.subs(lam, eigenvalue))
    x = sym.symbols('x')
    y = sym.symbols('y')
    z = sym.symbols('z')
    evec = sym.Matrix([x, y, z])
    print(eigen_matrix.subs(lam, eigenvalue) * evec)
    print(sym.solve((eigen_matrix.subs(lam, eigenvalue) * evec)))
    eigenvectors.append(sym.solve((eigen_matrix.subs(lam, eigenvalue) * evec)))
    print()

For eigenvalue  -5  the eigenvectors are 
Matrix([[3, -4, 2], [-2, 6, 2], [4, 2, 10]])
Matrix([[3*x - 4*y + 2*z], [-2*x + 6*y + 2*z], [4*x + 2*y + 10*z]])
{x: -2*z, y: -z}

For eigenvalue  3  the eigenvectors are 
Matrix([[-5, -4, 2], [-2, -2, 2], [4, 2, 2]])
Matrix([[-5*x - 4*y + 2*z], [-2*x - 2*y + 2*z], [4*x + 2*y + 2*z]])
{x: -2*z, y: 3*z}

For eigenvalue  6  the eigenvectors are 
Matrix([[-8, -4, 2], [-2, -5, 2], [4, 2, -1]])
Matrix([[-8*x - 4*y + 2*z], [-2*x - 5*y + 2*z], [4*x + 2*y - z]])
{x: z/16, y: 3*z/8}



In [13]:
# print the eigenvalues and eigenvectors of the coefficient matrix
eigenvalues_linalg, eigenvectors_linalgT = np.linalg.eig(A)
eigenvectors_linalg = eigenvectors_linalgT.T
print('The eigenvalues are ')
print(eigenvalues_linalg)
print('The eigenvectors (rows) are ')
print(eigenvectors_linalg)
print()

The eigenvalues are 
[-5.  3.  6.]
The eigenvectors (rows) are 
[[ 0.81649658  0.40824829 -0.40824829]
 [ 0.53452248 -0.80178373 -0.26726124]
 [ 0.05842062  0.35052374  0.93472998]]



In [14]:
# print the eigenvalues and eigenvectors of the coefficient matrix from Sympy
print(eigenvalues)
print(eigenvectors)

[-5, 3, 6]
[{x: -2*z, y: -z}, {x: -2*z, y: 3*z}, {x: z/16, y: 3*z/8}]


In [15]:
# check the eigenvalues and eigenvectors
for i in range(len(eigenvalues_linalg)):
    print('For eigenvalue ',eigenvalues_linalg[i],' matrix to be multiplied is ')
    print(A-eigenvalues_linalg[i]*np.identity(3))
    print('The eigenvector is ')
    print(eigenvectors_linalg[i])
    result = np.dot(A-eigenvalues_linalg[i]*np.identity(3),eigenvectors_linalg[i])
    print('The result of the matrix multiplication is ')
    print(result)
    sum_vals = 0.0
    for j in range(len(result)):
        sum_vals += result[j]
    print('The sum of the elements of the result is ')
    print(sum_vals)
    print()

For eigenvalue  -5.0000000000000036  matrix to be multiplied is 
[[ 3. -4.  2.]
 [-2.  6.  2.]
 [ 4.  2. 10.]]
The eigenvector is 
[ 0.81649658  0.40824829 -0.40824829]
The result of the matrix multiplication is 
[ 2.55351296e-15  2.10942375e-15 -8.88178420e-16]
The sum of the elements of the result is 
3.774758283725532e-15

For eigenvalue  2.9999999999999982  matrix to be multiplied is 
[[-5. -4.  2.]
 [-2. -2.  2.]
 [ 4.  2.  2.]]
The eigenvector is 
[ 0.53452248 -0.80178373 -0.26726124]
The result of the matrix multiplication is 
[-1.88737914e-15 -2.77555756e-15  7.77156117e-16]
The sum of the elements of the result is 
-3.885780586188048e-15

For eigenvalue  5.999999999999998  matrix to be multiplied is 
[[-8. -4.  2.]
 [-2. -5.  2.]
 [ 4.  2. -1.]]
The eigenvector is 
[0.05842062 0.35052374 0.93472998]
The result of the matrix multiplication is 
[6.66133815e-16 1.77635684e-15 1.44328993e-15]
The sum of the elements of the result is 
3.885780586188048e-15



## Eigenvalues and Eigenvectors of a Square Matrix

Diagonalization of a square matrix $A$ is the process of finding a diagonal matrix $\Lambda$ and an invertible matrix $S$ such that

$$A = S \Lambda S^{-1}$$

where $\Lambda$ is a diagonal matrix with the eigenvalues of $A$ as its diagonal elements and $S$ is a matrix with the eigenvectors of $A$ as its columns.

We can also therefore say that:

$$\Lambda = S^{-1} A S$$



In [14]:
print(A)

[[-2 -4  2]
 [-2  1  2]
 [ 4  2  5]]


In [15]:
print("Eigenvalues")
print(eigenvalues_linalg)
print("Eigenvector matrix with eigenvectors as columns")
print(eigenvectors_linalgT)
S = eigenvectors_linalgT

Eigenvalues
[-5.  3.  6.]
Eigenvector matrix with eigenvectors as columns
[[ 0.81649658  0.53452248  0.05842062]
 [ 0.40824829 -0.80178373  0.35052374]
 [-0.40824829 -0.26726124  0.93472998]]


In [16]:
Sinv = np.linalg.inv(S)
print("Inverse of eigenvector matrix with eigenvectors as columns")
print(Sinv)

Inverse of eigenvector matrix with eigenvectors as columns
[[ 0.7793831   0.61237244 -0.27835111]
 [ 0.62360956 -0.93541435  0.31180478]
 [ 0.51870433  0.          1.03740865]]


In [17]:
Lambda = np.diag(eigenvalues_linalg)
print("Eigenvalue matrix (diagonal)")
print(Lambda)

Lambda_Theory = np.dot(Sinv, np.dot(A,S))

print("Eigenvalue matrix (diagonal) calculated from Sinv, A, S")
print(Lambda_Theory)


Eigenvalue matrix (diagonal)
[[-5.  0.  0.]
 [ 0.  3.  0.]
 [ 0.  0.  6.]]
Eigenvalue matrix (diagonal) calculated from Sinv, A, S
[[-5.00000000e+00 -1.36538712e-15  3.87113080e-16]
 [-1.61672226e-16  3.00000000e+00 -5.69376217e-16]
 [ 1.55331165e-16 -2.41439647e-16  6.00000000e+00]]


In [18]:
A_Theory = np.dot(S, np.dot(Lambda, Sinv))
print("A calculated from S, Lambda, Sinv")
print(A_Theory)

A calculated from S, Lambda, Sinv
[[-2. -4.  2.]
 [-2.  1.  2.]
 [ 4.  2.  5.]]
