In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym

In [2]:
# 7.1

# Define the variables
x = sym.symbols('x', real=True)
y = sym.symbols('y', real=True)

z = x + sym.I*y

# Define the function
f = 2*z**2 + 4*z - 6*sym.I

# Compute the real and imaginary parts
u = sym.re(f)
v = sym.im(f)

print("u = ")
sym.pprint(u.simplify())
print()
print("v = ")
sym.pprint(v.simplify())
print()

# Compute the partial derivatives
ux = sym.diff(u, x)
uy = sym.diff(u, y)
vx = sym.diff(v, x)
vy = sym.diff(v, y)

print("ux = ")
sym.pprint(ux.simplify())
print()
print("uy = ")
sym.pprint(uy.simplify())
print()
print("vx = ")
sym.pprint(vx.simplify())
print()
print("vy = ")
sym.pprint(vy.simplify())
print() 


u = 
   2            2
2⋅x  + 4⋅x - 2⋅y 

v = 
4⋅x⋅y + 4⋅y - 6

ux = 
4⋅x + 4

uy = 
-4⋅y

vx = 
4⋅y

vy = 
4⋅x + 4


In [3]:
# 7.2

# Define the variables
x = sym.symbols('x', real=True)
y = sym.symbols('y', real=True)

z = x + sym.I*y

# Define the function
f = sym.re(z)

# Compute the real and imaginary parts
u = sym.re(f)
v = sym.im(f)

print("u = ")
sym.pprint(u.simplify())
print()
print("v = ")
sym.pprint(v.simplify())
print()

# Compute the partial derivatives
ux = sym.diff(u, x)
uy = sym.diff(u, y)
vx = sym.diff(v, x)
vy = sym.diff(v, y)

print("ux = ")
sym.pprint(ux.simplify())
print()
print("vy = ")
sym.pprint(vy.simplify())
print()
print("uy = ")
sym.pprint(uy.simplify())
print()
print("vx = ")
sym.pprint(vx.simplify())
print()

u = 
x

v = 
0

ux = 
1

vy = 
0

uy = 
0

vx = 
0


In [4]:
# 7.3

# Define the variables
x = sym.symbols('x', real=True)
y = sym.symbols('y', real=True)

z = x**2 + y**2

# Define the function
f = sym.re(z)

# Compute the real and imaginary parts
u = sym.re(f)
v = sym.im(f)

print("u = ")
sym.pprint(u.simplify())
print()
print("v = ")
sym.pprint(v.simplify())
print()

# Compute the partial derivatives
ux = sym.diff(u, x)
uy = sym.diff(u, y)
vx = sym.diff(v, x)
vy = sym.diff(v, y)

print("ux = ")
sym.pprint(ux.simplify())
print()
print("vy = ")
sym.pprint(vy.simplify())
print()
print("uy = ")
sym.pprint(uy.simplify())
print()
print("vx = ")
sym.pprint(vx.simplify())
print()

u = 
 2    2
x  + y 

v = 
0

ux = 
2⋅x

vy = 
0

uy = 
2⋅y

vx = 
0


In [5]:
# 7.4

# Define the variables
x = sym.symbols('x', real=True)
y = sym.symbols('y', real=True)
C = sym.symbols('C', real=True)

t = sym.symbols('t', real=True)
s = sym.symbols('s', real=True)
y0 = sym.symbols('y0', real=True)
x0 = sym.symbols('x0', real=True)

# Define the function
u = x**2 - y**2

# Compute the partial derivatives
ux = sym.diff(u, x)
uy = sym.diff(u, y)
uxx = sym.diff(ux, x)
uyy = sym.diff(uy, y)

print("ux = ")
sym.pprint(ux.simplify())
print()
print("uy = ")
sym.pprint(uy.simplify())
print()

print("uxx = ")
sym.pprint(uxx.simplify())
print()
print("uyy = ")
sym.pprint(uyy.simplify())
print()

# Check to see if the function is harmonic
print("uxx + uyy = ")
sym.pprint(uxx + uyy)
print()

# Find the conjugate harmonic function

vy = ux
vx = -uy

first_integrand = ux.subs(y, t)
first_integral = sym.integrate(first_integrand, t)
first_term = first_integral.subs(t, y) - first_integral.subs(t, y0)
print("first term = ")
sym.pprint(first_term.simplify())

second_integrand = -uy.subs(x, s).subs(y, y0)
second_integral = sym.integrate(second_integrand, s)
second_term = second_integral.subs(s, x) - second_integral.subs(s, x0)
print("second term = ")
sym.pprint(second_term.simplify())
print()

v = first_term + second_term + C
v = v.subs(y0, 0).subs(x0, 0)
print("v = ")
sym.pprint(v.simplify())
print()

f = u + sym.I*v
print("f = ")
sym.pprint(f.simplify())


ux = 
2⋅x

uy = 
-2⋅y

uxx = 
2

uyy = 
-2

uxx + uyy = 
0

first term = 
2⋅x⋅(y - y₀)
second term = 
2⋅y₀⋅(x - x₀)

v = 
C + 2⋅x⋅y

f = 
 2    2                
x  - y  + ⅈ⋅(C + 2⋅x⋅y)


In [6]:
# 7.5

# Define the variables
x = sym.symbols('x', real=True)
y = sym.symbols('y', real=True)
C = sym.symbols('C', real=True)

t = sym.symbols('t', real=True)
s = sym.symbols('s', real=True)
y0 = sym.symbols('y0', real=True)
x0 = sym.symbols('x0', real=True)

# Define the function
u = 8*x*y**3 - 8*x**3*y + x

# Compute the partial derivatives
ux = sym.diff(u, x)
uy = sym.diff(u, y)
uxx = sym.diff(ux, x)
uyy = sym.diff(uy, y)

print("ux = ")
sym.pprint(ux.simplify())
print()
print("uy = ")
sym.pprint(uy.simplify())
print()

print("uxx = ")
sym.pprint(uxx.simplify())
print()
print("uyy = ")
sym.pprint(uyy.simplify())
print()

# Check to see if the function is harmonic
print("uxx + uyy = ")
sym.pprint(uxx + uyy)
print()

# Find the conjugate harmonic function

vy = ux
vx = -uy

first_integrand = ux.subs(y, t)
first_integral = sym.integrate(first_integrand, t)
first_term = first_integral.subs(t, y) - first_integral.subs(t, y0)
print("first term = ")
sym.pprint(first_term.simplify())

second_integrand = -uy.subs(x, s).subs(y, y0)
second_integral = sym.integrate(second_integrand, s)
second_term = second_integral.subs(s, x) - second_integral.subs(s, x0)
print("second term = ")
sym.pprint(second_term.simplify())
print()

v = first_term + second_term + C
v = v.subs(y0, 0).subs(x0, 0)
print("v = ")
sym.pprint(v.simplify())
print()

f = u + sym.I*v
print("f = ")
sym.pprint(f.simplify())


ux = 
      2        3    
- 24⋅x ⋅y + 8⋅y  + 1

uy = 
    ⎛   2      2⎞
8⋅x⋅⎝- x  + 3⋅y ⎠

uxx = 
-48⋅x⋅y

uyy = 
48⋅x⋅y

uxx + uyy = 
0

first term = 
      2  2       2   2      4           4     
- 12⋅x ⋅y  + 12⋅x ⋅y₀  + 2⋅y  + y - 2⋅y₀  - y₀
second term = 
   4       2   2       4        2   2
2⋅x  - 12⋅x ⋅y₀  - 2⋅x₀  + 12⋅x₀ ⋅y₀ 

v = 
       4       2  2      4    
C + 2⋅x  - 12⋅x ⋅y  + 2⋅y  + y

f = 
     3          3         ⎛       4       2  2      4    ⎞
- 8⋅x ⋅y + 8⋅x⋅y  + x + ⅈ⋅⎝C + 2⋅x  - 12⋅x ⋅y  + 2⋅y  + y⎠
