# Eigenvalues and Eigenvectors

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym

# create a coefficient matrix
A = np.array([[4, 2], [-1, 1]])

As = sym.Matrix(A)


# Eigenvalues and Eigenvectors

Consider a square matrix $A$ of size $n \times n$. If there exists a vector $x$ of size $n \times 1$ and a scalar $\lambda$ such that

$$Ax = \lambda x$$

then $\lambda$ is called an eigenvalue of $A$ and $x$ is called an eigenvector of $A$ corresponding to the eigenvalue $\lambda$.

The eigenvalues of a matrix $A$ are the roots of the characteristic equation

$$det(A - \lambda I) = 0$$

where $I$ is the identity matrix of size $n \times n$.

The eigenvectors of a matrix $A$ are the vectors $x$ that satisfy the equation

$$(A - \lambda I)x = 0$$

for some eigenvalue $\lambda$.

The eigenvalues and eigenvectors of a matrix $A$ can be calculated using the `eig` function of the `numpy.linalg` module.

In [2]:
# print the eigenvalues and eigenvectors of the coefficient matrix
eigenvalues, eigenvectorsT = np.linalg.eig(A)

# the eigenvectors are the columns of the eigenvectorsT matrix
# taking the transpose of this matrix gives the eigenvectors as rows
eigenvectors = eigenvectorsT.T
print('The eigenvalues are ')
print(eigenvalues)
print('The eigenvectors (rows) are ')
print(eigenvectors)
print()

The eigenvalues are 
[3. 2.]
The eigenvectors (rows) are 
[[ 0.89442719 -0.4472136 ]
 [-0.70710678  0.70710678]]



## Direct Calculation of Eigenvalues and Eigenvectors using Sympy

In [3]:
lam = sym.symbols('lambda')
lambda_matrix = sym.Matrix([[lam, 0], [0, lam]])
print('The lambda matrix is ')
print(lambda_matrix)

The lambda matrix is 
Matrix([[lambda, 0], [0, lambda]])


In [4]:
eigen_matrix = As - lambda_matrix
print('The eigen matrix is ')
print(eigen_matrix)

The eigen matrix is 
Matrix([[4 - lambda, 2], [-1, 1 - lambda]])


In [5]:
det = eigen_matrix.det()
print('The determinant is ')
print(det)

The determinant is 
lambda**2 - 5*lambda + 6


In [6]:
eigenvalues = sym.solve(det)
print('The eigenvalues are ')
print(eigenvalues)

The eigenvalues are 
[2, 3]


In [7]:
# Now, for each eigenvalue, find the eigenvector

# Note that the result here will be a DICTIONARY

In [8]:
eigenvectors = []
for eigenvalue in eigenvalues:
    print('For eigenvalue ',eigenvalue,' the eigenvectors are ')
    print(eigen_matrix.subs(lam, eigenvalue))
    x = sym.symbols('x')
    y = sym.symbols('y')
    evec = sym.Matrix([x, y])
    print(eigen_matrix.subs(lam, eigenvalue) * evec)
    print(sym.solve((eigen_matrix.subs(lam, eigenvalue) * evec)))
    eigenvectors.append(sym.solve((eigen_matrix.subs(lam, eigenvalue) * evec)))
    print()

For eigenvalue  2  the eigenvectors are 
Matrix([[2, 2], [-1, -1]])
Matrix([[2*x + 2*y], [-x - y]])
{x: -y}

For eigenvalue  3  the eigenvectors are 
Matrix([[1, 2], [-1, -2]])
Matrix([[x + 2*y], [-x - 2*y]])
{x: -2*y}



In [9]:
# print the eigenvalues and eigenvectors of the coefficient matrix
eigenvalues_linalg, eigenvectors_linalgT = np.linalg.eig(A)
eigenvectors_linalg = eigenvectors_linalgT.T
print('The eigenvalues are ')
print(eigenvalues_linalg)
print('The eigenvectors (rows) are ')
print(eigenvectors_linalg)
print()

The eigenvalues are 
[3. 2.]
The eigenvectors (rows) are 
[[ 0.89442719 -0.4472136 ]
 [-0.70710678  0.70710678]]



In [10]:
# print the eigenvalues and eigenvectors of the coefficient matrix using Sympy
print(eigenvalues)
print(eigenvectors)

[2, 3]
[{x: -y}, {x: -2*y}]


In [11]:
# check the eigenvalues and eigenvectors
for i in range(len(eigenvalues_linalg)):
    print('For eigenvalue ',eigenvalues_linalg[i],' matrix to be multiplied is ')
    print(A-eigenvalues_linalg[i]*np.identity(2))
    print('The eigenvector is ')
    print(eigenvectors_linalg[i])
    result = np.dot(A-eigenvalues_linalg[i]*np.identity(2),eigenvectors_linalg[i])
    print('The result of the matrix multiplication is ')
    print(result)
    sum_vals = 0.0
    for j in range(len(result)):
        sum_vals += result[j]
    print('The sum of the elements of the result is ')
    print(sum_vals)
    print()

For eigenvalue  3.0  matrix to be multiplied is 
[[ 1.  2.]
 [-1. -2.]]
The eigenvector is 
[ 0.89442719 -0.4472136 ]
The result of the matrix multiplication is 
[0. 0.]
The sum of the elements of the result is 
0.0

For eigenvalue  2.0  matrix to be multiplied is 
[[ 2.  2.]
 [-1. -1.]]
The eigenvector is 
[-0.70710678  0.70710678]
The result of the matrix multiplication is 
[0. 0.]
The sum of the elements of the result is 
0.0



## Eigenvalues and Eigenvectors of a Square Matrix

Diagonalization of a square matrix $A$ is the process of finding a diagonal matrix $\Lambda$ and an invertible matrix $S$ such that

$$A = S \Lambda S^{-1}$$

where $\Lambda$ is a diagonal matrix with the eigenvalues of $A$ as its diagonal elements and $S$ is a matrix with the eigenvectors of $A$ as its columns.

We can also therefore say that:

$$\Lambda = S^{-1} A S$$



In [12]:
print(A)

[[ 4  2]
 [-1  1]]


In [13]:
print("Eigenvalues")
print(eigenvalues_linalg)
print("Eigenvector matrix with eigenvectors as columns")
print(eigenvectors_linalgT)
S = eigenvectors_linalgT

Eigenvalues
[3. 2.]
Eigenvector matrix with eigenvectors as columns
[[ 0.89442719 -0.70710678]
 [-0.4472136   0.70710678]]


In [14]:
Sinv = np.linalg.inv(S)
print("Inverse of eigenvector matrix with eigenvectors as columns")
print(Sinv)

Inverse of eigenvector matrix with eigenvectors as columns
[[2.23606798 2.23606798]
 [1.41421356 2.82842712]]


In [15]:
Lambda = np.diag(eigenvalues_linalg)
print("Eigenvalue matrix (diagonal)")
print(Lambda)

Lambda_Theory = np.dot(Sinv, np.dot(A,S))

print("Eigenvalue matrix (diagonal) calculated from Sinv, A, S")
print(Lambda_Theory)


Eigenvalue matrix (diagonal)
[[3. 0.]
 [0. 2.]]
Eigenvalue matrix (diagonal) calculated from Sinv, A, S
[[ 3.00000000e+00  1.26604879e-16]
 [-4.01761617e-19  2.00000000e+00]]


In [16]:
A_Theory = np.dot(S, np.dot(Lambda, Sinv))
print("A calculated from S, Lambda, Sinv")
print(A_Theory)

A calculated from S, Lambda, Sinv
[[ 4.  2.]
 [-1.  1.]]
