# Moment of Inertia Tensor

What is a tensor? A tensor is a mathematical object that describes a linear mapping between two vector spaces. So, for example, a 2x2 matrix is a tensor that maps a 2-dimensional vector to another 2-dimensional vector.  In other words, all of the transformation matrices that we have been using are tensors!

In our case, we are interested in the mapping between the angular momentum vector and the angular velocity vector. The tensor that describes this mapping is called the moment of inertia tensor. The moment of inertia tensor is a 3x3 matrix that is symmetric and positive definite.

The total angular momentum of a rigid body, about the origin, is given by:

$$\vec{L} = \sum_i m_i \vec{r}_i \times \vec{v}_i$$

where $\vec{r}_i$ is the position vector of the $i$th particle relative to the origin, and $\vec{v}_i$ is the velocity vector of the $i$th particle relative to the origin.  We can write the velocity as the cross product of the angular velocity and the position vector:

$$\vec{v}_i = \vec{\omega} \times \vec{r}_i$$

Substituting this into the equation for angular momentum gives:

$$\vec{L} = \sum_i m_i \vec{r}_i \times (\vec{\omega} \times \vec{r}_i)$$

We can use the usual rules for the cross product to rewrite this as:

$$\vec{L} = \sum_i m_i (\vec{r}_i \cdot \vec{r}_i) \vec{\omega} - \sum_i m_i (\vec{r}_i \cdot \vec{\omega}) \vec{r}_i$$

This formula can be written in matrix form as:

$$\vec{L} = \mathbf{I} \vec{\omega}$$

where $\mathbf{I}$ is the moment of inertia tensor.  The moment of inertia tensor is a 3x3 matrix that is symmetric and positive definite.  The diagonal elements of the moment of inertia tensor are called the principal moments of inertia.  The principal moments of inertia are the moments of inertia about the principal axes of the body.  The principal axes are the eigenvectors of the moment of inertia tensor.  The eigenvalues of the moment of inertia tensor are the principal moments of inertia.

Writing this equation out in components gives:

$$\begin{bmatrix} L_x \\ L_y \\ L_z \end{bmatrix} = \begin{bmatrix} I_{xx} & I_{xy} & I_{xz} \\ I_{yx} & I_{yy} & I_{yz} \\ I_{zx} & I_{zy} & I_{zz} \end{bmatrix} \begin{bmatrix} \omega_x \\ \omega_y \\ \omega_z \end{bmatrix}$$

where now we have that:

$$\begin{align} I_{xx} &= \sum_i m_i (y_i^2 + z_i^2) \\ I_{xy} &= -\sum_i m_i x_i y_i \\ I_{xz} &= -\sum_i m_i x_i z_i \\ I_{yx} &= -\sum_i m_i y_i x_i \\ I_{yy} &= \sum_i m_i (x_i^2 + z_i^2) \\ I_{yz} &= -\sum_i m_i y_i z_i \\ I_{zx} &= -\sum_i m_i z_i x_i \\ I_{zy} &= -\sum_i m_i z_i y_i \\ I_{zz} &= \sum_i m_i (x_i^2 + y_i^2) \end{align}$$

Writing these now in integral form gives:

$$\begin{align} I_{xx} &= \int (y^2 + z^2) \rho(x,y,z) dV \\ I_{xy} &= -\int x y \rho(x,y,z) dV \\ I_{xz} &= -\int x z \rho(x,y,z) dV \\ I_{yx} &= -\int y x \rho(x,y,z) dV \\ I_{yy} &= \int (x^2 + z^2) \rho(x,y,z) dV \\ I_{yz} &= -\int y z \rho(x,y,z) dV \\ I_{zx} &= -\int z x \rho(x,y,z) dV \\ I_{zy} &= -\int z y \rho(x,y,z) dV \\ I_{zz} &= \int (x^2 + y^2) \rho(x,y,z) dV \end{align}$$

where $\rho(x,y,z)$ is the mass density of the body.  Note that the integrals are over the entire volume of the body.

# Moment of Inertia Tensor for a Sphere

Let's now consider the moment of inertia tensor for a sphere.  We will assume that the sphere has uniform density $\rho$ and radius $R$.  We will also assume that the sphere is rotating about the $z$ axis.  In this case, the moment of inertia tensor is given by:

$$\mathbf{I} = \begin{bmatrix} I_{xx} & I_{xy} & I_{xz} \\ I_{yx} & I_{yy} & I_{yz} \\ I_{zx} & I_{zy} & I_{zz} \end{bmatrix} = \begin{bmatrix} \frac{2}{5} m R^2 & 0 & 0 \\ 0 & \frac{2}{5} m R^2 & 0 \\ 0 & 0 & \frac{2}{5} m R^2 \end{bmatrix}$$

where $m$ is the mass of the sphere.  Note that the moment of inertia tensor is diagonal.  This means that the principal axes of the sphere are the same as the coordinate axes.  The principal moments of inertia are all equal to $\frac{2}{5} m R^2$.

Consider evaluating $I_{zz}$.  We have that:

$$I_{zz} = \int (x^2 + y^2) \rho(x,y,z) dV$$

We can write the mass density as:

$$\rho(x,y,z) = \frac{m}{V}$$

where $V$ is the volume of the sphere.  Substituting this into the equation for $I_{zz}$ gives:

$$I_{zz} = \frac{m}{V} \int (x^2 + y^2) dV$$

We can write the volume element in spherical coordinates as:

$$dV = r^2 \sin \theta dr d\theta d\phi$$

Substituting this into the equation for $I_{zz}$ gives:

$$I_{zz} = \frac{m}{V} \int_0^{2\pi} \int_0^\pi \int_0^R (r^2 \sin^2 \theta \cos^2 \phi + r^2 \sin^2 \theta \sin^2 \phi) r^2 \sin \theta dr d\theta d\phi$$

Evaluating this integral gives:

$$I_{zz} = \frac{m}{V} \int_0^{2\pi} \int_0^\pi \int_0^R r^4 \sin^3 \theta dr d\theta d\phi = \frac{m}{V} \int_0^{2\pi} \int_0^\pi \frac{R^5}{5} \sin^3 \theta d\theta d\phi = \frac{2}{5} m R^2$$

where we have used the fact that:

$$\int_0^{2\pi} \int_0^\pi \sin^3 \theta d\theta d\phi = 2 \pi$$

and:

$$V = \frac{4}{3} \pi R^3$$

We can use the same method to evaluate the other components of the moment of inertia tensor.  We find that:

$$\mathbf{I} = \begin{bmatrix} \frac{2}{5} m R^2 & 0 & 0 \\ 0 & \frac{2}{5} m R^2 & 0 \\ 0 & 0 & \frac{2}{5} m R^2 \end{bmatrix}$$

# Moment of Inertia Tensor for a Cube

Let's now consider the moment of inertia tensor for a cube.  We will assume that the cube has uniform density $\rho$ and side length $L$.  We will also assume that the cube is rotating about the $z$ axis, and the origin is the center of mass of the cube.  In this case, the moment of inertia tensor is given by:

$$\mathbf{I} = \begin{bmatrix} I_{xx} & I_{xy} & I_{xz} \\ I_{yx} & I_{yy} & I_{yz} \\ I_{zx} & I_{zy} & I_{zz} \end{bmatrix} = \begin{bmatrix} \frac{1}{6} m L^2 & 0 & 0 \\ 0 & \frac{1}{6} m L^2 & 0 \\ 0 & 0 & \frac{1}{6} m L^2 \end{bmatrix}$$

where $m$ is the mass of the cube.  Note that the moment of inertia tensor is diagonal.  This means that the principal axes of the cube are the same as the coordinate axes.  The principal moments of inertia are $\frac{1}{6} m L^2$, $\frac{1}{6} m L^2$, and $\frac{1}{6} m L^2$.

Consider evaluating $I_{xx}$.  We have that:

$$I_{xx} = \int (y^2 + z^2) \rho(x,y,z) dV$$

We can write the mass density as:

$$\rho(x,y,z) = \frac{m}{V}$$

where $V$ is the volume of the cube.  Substituting this into the equation for $I_{xx}$ gives:

$$I_{xx} = \frac{m}{V} \int (y^2 + z^2) dV$$

We can write the volume element in Cartesian coordinates as:

$$dV = dx dy dz$$

Substituting this into the equation for $I_{xx}$ gives:

$$I_{xx} = \frac{m}{V} \int_{-L/2}^{L/2} \int_{-L/2}^{L/2} \int_{-L/2}^{L/2} (y^2 + z^2) dx dy dz$$

Evaluating this integral gives:

$$I_{xx} = \frac{mL}{V} \int_{-L/2}^{L/2} \int_{-L/2}^{L/2} \left( y^2+z^2 \right) dy dz = \frac{1}{6} m L^2$$

where we have used the fact that:

$$\int_{-L/2}^{L/2} y^2 dy = \int_{-L/2}^{L/2} z^2 dz = \frac{L^3}{12}$$

and:

$$V = L^3$$

Consider now evaluating $I_{xy}$.  We have that:

$$I_{xy} = -\int x y \rho(x,y,z) dV$$

Substituting in the mass density gives:

$$I_{xy} = -\frac{m}{V} \int x y dx dy dz$$

Evaluating this integral gives:

$$I_{xy} = -\frac{m}{V} \int_{-L/2}^{L/2} \int_{-L/2}^{L/2} \int_{-L/2}^{L/2} x y dx dy dz = 0$$

where we have used the fact that:

$$\int_{-L/2}^{L/2} x y dx = 0$$

We can use the same method to evaluate the other components of the moment of inertia tensor.



# Moment of Inertia Tensor for 2D Rectangle

Let's now consider the moment of inertia tensor for a 2D rectangle.  We will assume that the rectangle has uniform density $\rho$ and side lengths $L_x$ and $L_y$.  We will also assume that the rectangle is rotating about the $z$ axis, that the origin is the center of mass of the rectangle.  In this case, the moment of inertia tensor is given by:

$$\mathbf{I} = \begin{bmatrix} I_{xx} & I_{xy} & I_{xz} \\ I_{yx} & I_{yy} & I_{yz} \\ I_{zx} & I_{zy} & I_{zz} \end{bmatrix} = \begin{bmatrix} \frac{1}{12} m L_y^2 & 0 & 0 \\ 0 & \frac{1}{12} m L_x^2 & 0 \\ 0 & 0 & \frac{1}{12} m (L_x^2 + L_y^2) \end{bmatrix}$$

where $m$ is the mass of the rectangle.  Note that the moment of inertia tensor is diagonal.  This means that the principal axes of the rectangle are the same as the coordinate axes.  The principal moments of inertia are $\frac{1}{12} m L_y^2$, $\frac{1}{12} m L_x^2$, and $\frac{1}{12} m (L_x^2 + L_y^2)$.

Consider evaluating $I_{xx}$.  We have that:

$$I_{xx} = \int (y^2 + z^2) \rho(x,y,z) dV$$

We can write the mass density as:

$$\rho(x,y,z) = \frac{m}{V}$$

where $V$ is the volume of the rectangle.  Substituting this into the equation for $I_{xx}$ gives:

$$I_{xx} = \frac{m}{V} \int (y^2 + z^2) dV$$

We can write the volume element in Cartesian coordinates as:

$$dV = dx dy dz$$

Substituting this into the equation for $I_{xx}$ gives:

$$I_{xx} = \frac{m}{V} \int_{-L_x/2}^{L_x/2} \int_{-L_y/2}^{L_y/2} \int_{-L_z/2}^{L_z/2} (y^2 + z^2) dx dy dz$$

Evaluating this integral gives:

$$I_{xx} = \frac{mL_x}{V} \int_{-L_x/2}^{L_x/2} \int_{-L_y/2}^{L_y/2} \left( y^2 + z^2 \right) dy dz = \frac{1}{12} m (L_y^2 + L_z^2)$$

where we have used the fact that:

$$\int_{-L_y/2}^{L_y/2} y^2 dy = \frac{L_y^3}{12}, \int_{-L_z/2}^{L_z/2} z^2 dz = \frac{L_z^3}{12}$$

and:

$$V = L_x L_y L_z$$

Taking the limit as $L_z \rightarrow 0$ gives:

$$I_{xx} = \frac{1}{12} m L_y^2$$

Similarly, we can show that:

$$I_{yy} = \frac{1}{12} m L_x^2$$

Consider now evaluating $I_{zz}$.  We have that:

$$I_{zz} = \int (x^2 + y^2) \rho(x,y,z) dV$$

We can write the mass density as:

$$\rho(x,y,z) = \frac{m}{V}$$

where $V$ is the volume of the rectangle.  Substituting this into the equation for $I_{zz}$ gives:

$$I_{zz} = \frac{m}{V} \int (x^2 + y^2) dV$$

We can write the volume element in Cartesian coordinates as:

$$dV = dx dy dz$$

Substituting this into the equation for $I_{zz}$ gives:

$$I_{zz} = \frac{m}{V} \int_{-L_x/2}^{L_x/2} \int_{-L_y/2}^{L_y/2} \int_{-L_z/2}^{L_z/2} (x^2 + y^2) dx dy dz$$

Evaluating this integral gives:

$$I_{zz} = \frac{mL_z}{V} \int_{-L_x/2}^{L_x/2} \int_{-L_y/2}^{L_y/2} \left(x^2 + y^2 \right) dx dy = \frac{1}{12} m (L_x^2 + L_y^2)$$

where we have used the fact that:

$$\int_{-L_x/2}^{L_x/2} x^2 dx = \frac{L_x^3}{12}, \int_{-L_y/2}^{L_y/2} y^2 dy = \frac{L_y^3}{12}$$

and:

$$V = L_x L_y L_z$$

Taking the limit as $L_z \rightarrow 0$ gives:

$$I_{zz} = \frac{1}{12} m (L_x^2 + L_y^2)$$

# Parallel Axis Theorem

The parallel axis theorem is a useful tool for calculating the moment of inertia tensor for a body that is rotating about an axis that does not pass through the center of mass.  The parallel axis theorem states that:

$$\mathbf{I} = \mathbf{I}_{cm} + m \mathbf{d} \mathbf{d}$$

where $\mathbf{I}_{cm}$ is the moment of inertia tensor about the center of mass, $m$ is the mass of the body, and $\mathbf{d}$ is the vector from the center of mass to the axis of rotation.  Note that $\mathbf{d} \mathbf{d}$ is the outer product of $\mathbf{d}$ with itself.  This is a 3x3 matrix.  The outer product of two vectors is also called the dyadic product.

## Outer Product

The outer product of two vectors is a matrix.  I am going to leave out the derivation of the outer product here, but you can find it in any linear algebra textbook.  The result that we need here is:

$$\left( \mathbf{d} \mathbf{d} \right)_{ij} = \left(\sum_{k=1}^3 d_k d_k \right) \delta_{ij} - d_i d_j)$$

where $\delta_{ij}$ is the Kronecker delta.  The Kronecker delta is defined as:
    
$$\delta_{ij} = \begin{cases} 1 & i = j \\ 0 & i \ne j \end{cases}$$



## Parallel Axis Theorem, in terms of the Moment of Inertia Tensor

In terms of the moment of inertia tensor, the parallel axis theorem states that:

$$I_{ij} = I_{cm,ij} + m \left( \left( \sum_{k=1}^3 d_k d_k \right) \delta_{ij} - d_i d_j \right)$$


# Moment of Inertia Tensor for a Cube around one of its Corners

Let's now consider the moment of inertia tensor for a cube that is rotating around an axis that passes through one of its corners.  We will assume that the cube has uniform density $\rho$ and side length $L$. 

Note that the axes of rotation here will be the principal axes of the cube.

Using the parallel axis theorem, we can write that:

$$\vec{d} = \begin{bmatrix} L/2 \\ L/2 \\ L/2 \end{bmatrix}$$

Then, we have that:

$$I_{ij} = I_{cm,ij} + m (\left(\sum_{k=1}^3 d_k d_k \right) \delta_{ij} - d_i d_j)$$
$$ = I_{cm,ij} + m L^2 \left(\delta{ij}\frac{3}{4} - \frac{1}{4}\right)$$

where we have used the fact that:

$$\left(\sum_{k=1}^3 d_k d_k \right) = \frac{3}{4} L^2$$

and:

$$d_i d_j = \frac{1}{4} L^2 \delta_{ij}$$

Thus, we have that:

$$I_{ij} = \begin{bmatrix} \frac{1}{6} m L^2 & 0 & 0 \\ 0 & \frac{1}{6} m L^2 & 0 \\ 0 & 0 & \frac{1}{6} m L^2 \end{bmatrix} + m L^2 \begin{bmatrix} \frac{1}{2} & \frac{-1}{4} & \frac{-1}{4} \\ \frac{-1}{4} & \frac{1}{2} & \frac{-1}{4} \\
\frac{-1}{4} & \frac{-1}{4} & \frac{1}{2} \end{bmatrix} $$

$$I_{ij} = mL^2 \begin{bmatrix} \frac{2}{3} & \frac{-1}{4} & \frac{-1}{4} \\ \frac{-1}{4} & \frac{2}{3} & \frac{-1}{4} \\ \frac{-1}{4} & \frac{-1}{4} & \frac{2}{3} \end{bmatrix}$$


In [1]:
# Let us find the eigenvalues and eigenvectors of this matrix, assuming m = 1kg and L = 1m
import numpy as np
%matplotlib notebook

I = np.array([[2/3, -1/4, -1/4], [-1/4, 2/3, -1/4], [-1/4, -1/4, 2/3]])

eigvals, eigvecsT = np.linalg.eig(I)

print(eigvals)

print(eigvecsT)

a = eigvecsT[:,0]
b = eigvecsT[:,1]
c = eigvecsT[:,2]

import matplotlib.pyplot as plt

fig = plt.figure(figsize=(10,10))
ax = fig.add_subplot(111, projection='3d')

# Draw the axes
#ax.quiver(0, 0, 0, 1, 0, 0, color='k')
#ax.quiver(0, 0, 0, 0, 1, 0, color='k')
#ax.quiver(0, 0, 0, 0, 0, 1, color='k')

# Draw a cube centered at the origin with side length 1
r = [0.0,0.0,0.0]
d = 0.5
ax.plot([r[0]-d, r[0]+d, r[0]+d, r[0]-d, r[0]-d], [r[1]-d, r[1]-d, r[1]+d, r[1]+d, r[1]-d], [r[2]-d, r[2]-d, r[2]-d, r[2]-d, r[2]-d], color='k')
ax.plot([r[0]-d, r[0]+d, r[0]+d, r[0]-d, r[0]-d], [r[1]-d, r[1]-d, r[1]+d, r[1]+d, r[1]-d], [r[2]+d, r[2]+d, r[2]+d, r[2]+d, r[2]+d], color='k')
ax.plot([r[0]-d, r[0]-d], [r[1]-d, r[1]-d], [r[2]-d, r[2]+d], color='k')
ax.plot([r[0]+d, r[0]+d], [r[1]-d, r[1]-d], [r[2]-d, r[2]+d], color='k')
ax.plot([r[0]+d, r[0]+d], [r[1]+d, r[1]+d], [r[2]-d, r[2]+d], color='k')
ax.plot([r[0]-d, r[0]-d], [r[1]+d, r[1]+d], [r[2]-d, r[2]+d], color='k')


# Set limits

ax.set_xlim([-1, 1])
ax.set_ylim([-1, 1])
ax.set_zlim([-1, 1])


# Draw the eigenvectors
r = [0.5,0.5,0.5]
ax.quiver(r[0], r[1], r[2], a[0], a[1], a[2], color='r')
ax.quiver(r[0], r[1], r[2], b[0], b[1], b[2], color='b')
ax.quiver(r[0], r[1], r[2], c[0], c[1], c[2], color='g')


[0.91666667 0.16666667 0.91666667]
[[ 0.81649658 -0.57735027  0.44507153]
 [-0.40824829 -0.57735027 -0.81535403]
 [-0.40824829 -0.57735027  0.3702825 ]]


<IPython.core.display.Javascript object>

# Moment of Inertia Tensor for a Plate around one of its Corners

Let's now consider the moment of inertia tensor for a plate that is rotating around an axis that passes through one of its corners.  We will assume that the plate has uniform density $\rho$ and side lengths $L_x$ and $L_y$.

Note that the axes of rotation here will be the principal axes of the plate.

Using the parallel axis theorem, we can write that:

$$\vec{d} = \begin{bmatrix} L_x/2 \\ L_y/2 \\ 0 \end{bmatrix}$$

Then, we have that:

$$I_{ij} = I_{cm,ij} + m (\left(\sum_{k=1}^3 d_k d_k \right) \delta_{ij} - d_i d_j)$$

$$ = I_{cm,ij} + m \begin{bmatrix} \frac{L_y^2}{4} & -\frac{L_x L_y}{4} & 0 \\ -\frac{L_x L_y}{4} & \frac{L_x^2}{4} & 0 \\ 0 & 0 & \frac{L_x^2 + L_y^2}{4} \end{bmatrix}$$

where we have used the fact that:

$$\left(\sum_{k=1}^3 d_k d_k \right) \delta_{ij} = \begin{bmatrix} \frac{L_x^2+L_y^2}{4} & 0 & 0 \\ 0 & \frac{L_x^2 + L_y^2}{4} & 0 \\ 0 & 0 & \frac{L_x^2 + L_y^2}{4} \end{bmatrix}$$

and:

$$d_i d_j = \begin{bmatrix} \frac{L_x^2}{4} & \frac{L_x L_y}{4} & 0 \\  \frac{L_x L_y}{4} & \frac{L_y^2}{4} & 0 \\ 0 & 0 & 0 \end{bmatrix}$$

Thus, we have that:

$$I_{ij} = \begin{bmatrix} \frac{1}{12} m L_y^2 & 0 & 0 \\ 0 & \frac{1}{12} m L_x^2 & 0 \\ 0 & 0 & \frac{1}{12} m (L_x^2 + L_y^2) \end{bmatrix} + m \begin{bmatrix} \frac{L_y^2}{4} & -\frac{L_x L_y}{4} & 0 \\ -\frac{L_x L_y}{4} & \frac{L_x^2}{4} & 0 \\ 0 & 0 & \frac{L_x^2 + L_y^2}{4} \end{bmatrix} $$

$$I_{ij} = m \begin{bmatrix} \frac{1}{3} L_y^2 & -\frac{1}{4} L_x L_y & 0 \\ -\frac{1}{4} L_x L_y & \frac{1}{3} L_x^2 & 0 \\ 0 & 0 & \frac{1}{3} (L_x^2 + L_y^2) \end{bmatrix}$$

In [2]:
# Let us find the eigenvalues and eigenvectors of this matrix, assuming m = 1kg, L_x = 1m, and L_y = 2m

I = np.array([[4/3, -2/4, 0], [-2/4, 1/3, 0], [0, 0, 5/3]])

eigvals, eigvecsT = np.linalg.eig(I)

print(eigvals)

print(eigvecsT)

a = eigvecsT[:,0]
b = eigvecsT[:,1]
c = eigvecsT[:,2]

import matplotlib.pyplot as plt

fig = plt.figure(figsize=(10,10))
ax = fig.add_subplot(111, projection='3d')

# Draw the axes
#ax.quiver(0, 0, 0, 1, 0, 0, color='k')
#ax.quiver(0, 0, 0, 0, 1, 0, color='k')
#ax.quiver(0, 0, 0, 0, 0, 1, color='k')

# Draw a plate centered at the origin with side lengths 1 and 1
r = [0.0,0.0,0.0]
dx = 0.5
dy = 1.0
ax.plot([r[0]-dx, r[0]+dx, r[0]+dx, r[0]-dx, r[0]-dx], [r[1]-dy, r[1]-dy, r[1]+dy, r[1]+dy, r[1]-dy], [r[2], r[2], r[2], r[2], r[2]], color='k')

# Set limits
ax.set_xlim([-2, 2])
ax.set_ylim([-2, 2])
ax.set_zlim([-2, 2])

# Draw the eigenvectors
r = [0.5,1.0,0.0]
ax.quiver(r[0], r[1], r[2], a[0], a[1], a[2], color='r')
ax.quiver(r[0], r[1], r[2], b[0], b[1], b[2], color='b')
ax.quiver(r[0], r[1], r[2], c[0], c[1], c[2], color='g')

[1.54044011 0.12622655 1.66666667]
[[ 0.92387953  0.38268343  0.        ]
 [-0.38268343  0.92387953  0.        ]
 [ 0.          0.          1.        ]]


<IPython.core.display.Javascript object>

In [3]:
# Calculate the volume of a sphere, numerically

import numpy as np

N = 1000000
x = np.random.rand(N)
y = np.random.rand(N)
z = np.random.rand(N)

r = np.sqrt(x**2 + y**2 + z**2)

V = np.sum(r < 1)/N*8

print(V)

4.196672
