# Systems of Linear Equations

Consider a system of $m$ linear equations in $n$ unknowns

$$\begin{align*}
a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n &= b_1 \\
a_{21}x_1 + a_{22}x_2 + \cdots + a_{2n}x_n &= b_2 \\
\vdots \\
a_{m1}x_1 + a_{m2}x_2 + \cdots + a_{mn}x_n &= b_m
\end{align*}$$

This system can be written in matrix form as

$$Ax = b$$

where

$$A = \begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \end{bmatrix}$$

$$x = \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{bmatrix}$$

$$b = \begin{bmatrix} b_1 \\ b_2 \\ \vdots \\ b_m \end{bmatrix}$$

The solution of the system of linear equations $Ax = b$ can be calculated using the `solve` function of the `numpy.linalg` module.

The inverse of a matrix $A$ can be calculated using the `inv` function of the `numpy.linalg` module.

The determinant of a matrix $A$ can be calculated using the `det` function of the `numpy.linalg` module.

# Eigenvalues and Eigenvectors

Consider a square matrix $A$ of size $n \times n$. If there exists a vector $x$ of size $n \times 1$ and a scalar $\lambda$ such that

$$Ax = \lambda x$$

then $\lambda$ is called an eigenvalue of $A$ and $x$ is called an eigenvector of $A$ corresponding to the eigenvalue $\lambda$.

The eigenvalues of a matrix $A$ are the roots of the characteristic equation

$$det(A - \lambda I) = 0$$

where $I$ is the identity matrix of size $n \times n$.

The eigenvectors of a matrix $A$ are the vectors $x$ that satisfy the equation

$$(A - \lambda I)x = 0$$

for some eigenvalue $\lambda$.

The eigenvalues and eigenvectors of a matrix $A$ can be calculated using the `eig` function of the `numpy.linalg` module.

Consider the following matrix

$$A = \begin{bmatrix} 0 & 1 \\ -2 & -3 \end{bmatrix}$$

Consider also a constant vector $c$ of size $3 \times 1$

$$c = \begin{bmatrix} 5 \\ -3 \end{bmatrix}$$

The solution of the system of linear equations $Ax = c$ can be calculated using the `solve` function of the `numpy.linalg` module.

The inverse of a matrix $A$ can be calculated using the `inv` function of the `numpy.linalg` module.

The determinant of a matrix $A$ can be calculated using the `det` function of the `numpy.linalg` module.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# create a coefficient matrix
A = np.array([[0, 1], [-2, -3]])

# create a constant vector
c = np.array([5, -3])

# solve the system of linear equations
x = np.linalg.solve(A, c)

# print the solution
print('The solution vector is ',x)

The solution vector is  [-6.  5.]


In [2]:
# calculate the inverse of the coefficient matrix
A_inv = np.linalg.inv(A)

# calculate the solution vector by multiplying the inverse with the constant vector
x = np.dot(A_inv, c)

# print the solution
print('The solution vector is ',x)

The solution vector is  [-6.  5.]


In [3]:
# print the inverse of the coefficient matrix
print('The inverse of the coefficient matrix is ')
print(A_inv)
print()

# print the determinant of the coefficient matrix
print('The determinant is ',np.linalg.det(A))
print()

# print the rank of the coefficient matrix
print('The rank is ',np.linalg.matrix_rank(A))
print()

# print the eigenvalues and eigenvectors of the coefficient matrix
eigenvalues, eigenvectorsT = np.linalg.eig(A)

# the eigenvectors are the columns of the eigenvectorsT matrix
# taking the transpose of this matrix gives the eigenvectors as rows
eigenvectors = eigenvectorsT.T
print('The eigenvalues are ')
print(eigenvalues)
print('The eigenvectors (rows) are ')
print(eigenvectors)
print()

# print the norm of the coefficient matrix
print('The norm is ',np.linalg.norm(A))
print()

# print the condition number of the coefficient matrix
print('The condition number is ',np.linalg.cond(A))
print()

The inverse of the coefficient matrix is 
[[-1.5 -0.5]
 [ 1.   0. ]]

The determinant is  2.0

The rank is  2

The eigenvalues are 
[-1. -2.]
The eigenvectors (rows) are 
[[ 0.70710678 -0.70710678]
 [-0.4472136   0.89442719]]

The norm is  3.7416573867739413

The condition number is  6.8541019662496865


In [4]:
# create a coefficient matrix using Sympy
import sympy as sym
As = sym.Matrix([[0, 1], [-2, -3]])

cs = sym.Matrix([5, -3])

print('The coefficient matrix is ')
print(As)

# calculate the inverse of the coefficient matrix
As_inv = As.inv()
print('The inverse of the coefficient matrix is ')
print(As_inv)

# calculate the solution vector by multiplying the inverse with the constant vector
xs = As_inv * cs

# print the solution
print('The solution vector is ')
print(xs)


The coefficient matrix is 
Matrix([[0, 1], [-2, -3]])
The inverse of the coefficient matrix is 
Matrix([[-3/2, -1/2], [1, 0]])
The solution vector is 
Matrix([[-6], [5]])


In [5]:
lam = sym.symbols('lambda')
lambda_matrix = sym.Matrix([[lam, 0], [0, lam]])
print('The lambda matrix is ')
print(lambda_matrix)

The lambda matrix is 
Matrix([[lambda, 0], [0, lambda]])


In [6]:
eigen_matrix = As - lambda_matrix
print('The eigen matrix is ')
print(eigen_matrix)

The eigen matrix is 
Matrix([[-lambda, 1], [-2, -lambda - 3]])


In [7]:
det = eigen_matrix.det()
print('The determinant is ')
print(det)

The determinant is 
lambda**2 + 3*lambda + 2


In [8]:
eigenvalues = sym.solve(det)
print('The eigenvalues are ')
print(eigenvalues)

The eigenvalues are 
[-2, -1]


In [9]:
eigenvectors = []
for eigenvalue in eigenvalues:
    print('For eigenvalue ',eigenvalue,' the eigenvectors are ')
    print(eigen_matrix.subs(lam, eigenvalue))
    x = sym.symbols('x')
    y = sym.symbols('y')
    evec = sym.Matrix([x, y])
    print(eigen_matrix.subs(lam, eigenvalue) * evec)
    print(sym.solve((eigen_matrix.subs(lam, eigenvalue) * evec)))
    eigenvectors.append(sym.solve((eigen_matrix.subs(lam, eigenvalue) * evec)))
    print()

For eigenvalue  -2  the eigenvectors are 
Matrix([[2, 1], [-2, -1]])
Matrix([[2*x + y], [-2*x - y]])
{x: -y/2}

For eigenvalue  -1  the eigenvectors are 
Matrix([[1, 1], [-2, -2]])
Matrix([[x + y], [-2*x - 2*y]])
{x: -y}


In [10]:
# print the eigenvalues and eigenvectors of the coefficient matrix
eigenvalues_linalg, eigenvectors_linalgT = np.linalg.eig(A)
eigenvectors_linalg = eigenvectors_linalgT.T
print('The eigenvalues are ')
print(eigenvalues_linalg)
print('The eigenvectors (rows) are ')
print(eigenvectors_linalg)
print()

The eigenvalues are 
[-1. -2.]
The eigenvectors (rows) are 
[[ 0.70710678 -0.70710678]
 [-0.4472136   0.89442719]]


In [11]:
print(eigenvalues)
print(eigenvectors)

[-2, -1]
[{x: -y/2}, {x: -y}]


In [12]:
# check the eigenvalues and eigenvectors
for i in range(len(eigenvalues_linalg)):
    print('For eigenvalue ',eigenvalues_linalg[i],' matrix to be multiplied is ')
    print(A-eigenvalues_linalg[i]*np.identity(2))
    print('The eigenvector is ')
    print(eigenvectors_linalg[i])
    result = np.dot(A-eigenvalues_linalg[i]*np.identity(2),eigenvectors_linalg[i])
    print('The result of the matrix multiplication is ')
    print(result)
    sum_vals = 0.0
    for j in range(len(result)):
        sum_vals += result[j]
    print('The sum of the elements of the result is ')
    print(sum_vals)
    print()

For eigenvalue  -1.0  matrix to be multiplied is 
[[ 1.  1.]
 [-2. -2.]]
The eigenvector is 
[ 0.70710678 -0.70710678]
The result of the matrix multiplication is 
[0. 0.]
The sum of the elements of the result is 
0.0

For eigenvalue  -2.0  matrix to be multiplied is 
[[ 2.  1.]
 [-2. -1.]]
The eigenvector is 
[-0.4472136   0.89442719]
The result of the matrix multiplication is 
[0. 0.]
The sum of the elements of the result is 
0.0


In [13]:
print(A)

[[ 0  1]
 [-2 -3]]


In [14]:
print("Eigenvalues")
print(eigenvalues_linalg)
print("Eigenvector matrix with eigenvectors as columns")
print(eigenvectors_linalgT)
S = eigenvectors_linalgT

Eigenvalues
[-1. -2.]
Eigenvector matrix with eigenvectors as columns
[[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


In [15]:
Sinv = np.linalg.inv(S)
print("Inverse of eigenvector matrix with eigenvectors as columns")
print(Sinv)

Inverse of eigenvector matrix with eigenvectors as columns
[[2.82842712 1.41421356]
 [2.23606798 2.23606798]]


In [16]:
Lambda = np.diag(eigenvalues_linalg)
print("Eigenvalue matrix (diagonal)")
print(Lambda)

Lambda_Theory = np.dot(Sinv, np.dot(A,S))

print("Eigenvalue matrix (diagonal) calculated from Sinv, A, S")
print(Lambda_Theory)


Eigenvalue matrix (diagonal)
[[-1.  0.]
 [ 0. -2.]]
Eigenvalue matrix (diagonal) calculated from Sinv, A, S
[[-1.00000000e+00 -4.36247471e-17]
 [ 6.33024397e-17 -2.00000000e+00]]


In [17]:
A_Theory = np.dot(S, np.dot(Lambda, Sinv))
print("A calculated from S, Lambda, Sinv")
print(A_Theory)

A calculated from S, Lambda, Sinv
[[ 4.53932125e-17  1.00000000e+00]
 [-2.00000000e+00 -3.00000000e+00]]
