In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Eigenvalues and Eigenvectors

Consider a square matrix $A$ of size $n \times n$. If there exists a vector $x$ of size $n \times 1$ and a scalar $\lambda$ such that

$$Ax = \lambda x$$

then $\lambda$ is called an eigenvalue of $A$ and $x$ is called an eigenvector of $A$ corresponding to the eigenvalue $\lambda$.

The eigenvalues of a matrix $A$ are the roots of the characteristic equation

$$det(A - \lambda I) = 0$$

where $I$ is the identity matrix of size $n \times n$.

The eigenvectors of a matrix $A$ are the vectors $x$ that satisfy the equation

$$(A - \lambda I)x = 0$$

for some eigenvalue $\lambda$.

The eigenvalues and eigenvectors of a matrix $A$ can be calculated using the `eig` function of the `numpy.linalg` module.

Consider the following matrix

$$A = \begin{bmatrix} -2 & -4 & 2 \\ -2 & 1 & 2 \\ 4 & 2 & 5 \end{bmatrix}$$

Consider also a constant vector $c$ of size $3 \times 1$

$$c = \begin{bmatrix} 5 \\ -3 \\ 4 \end{bmatrix}$$

The solution of the system of linear equations $Ax = c$ can be calculated using the `solve` function of the `numpy.linalg` module.

The inverse of a matrix $A$ can be calculated using the `inv` function of the `numpy.linalg` module.

The determinant of a matrix $A$ can be calculated using the `det` function of the `numpy.linalg` module.

In [2]:
# create a coefficient matrix
A = np.array([[-2, -4, 2], [-2, 1, 2], [4, 2, 5]])
#A = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])

# create a constant vector
c = np.array([5, -3, 4])

# solve the system of linear equations
x = np.linalg.solve(A, c)

# print the solution
print('The solution vector is ',x)

The solution vector is  [ 1.18888889 -1.6         0.48888889]


In [3]:
# calculate the inverse of the coefficient matrix
A_inv = np.linalg.inv(A)

# calculate the solution vector by multiplying the inverse with the constant vector
x = np.dot(A_inv, c)

# print the solution
print('The solution vector is ',x)

The solution vector is  [ 1.18888889 -1.6         0.48888889]


In [4]:
# print the inverse of the coefficient matrix
print('The inverse of the coefficient matrix is ')
print(A_inv)
print()

# print the determinant of the coefficient matrix
print('The determinant is ',np.linalg.det(A))
print()

# print the rank of the coefficient matrix
print('The rank is ',np.linalg.matrix_rank(A))
print()

# print the eigenvalues and eigenvectors of the coefficient matrix
eigenvalues, eigenvectorsT = np.linalg.eig(A)
eigenvectors = eigenvectorsT.T
print('The eigenvalues are ')
print(eigenvalues)
print('The eigenvectors (rows) are ')
print(eigenvectors)
print()

# print the norm of the coefficient matrix
print('The norm is ',np.linalg.norm(A))
print()

# print the condition number of the coefficient matrix
print('The condition number is ',np.linalg.cond(A))
print()

The inverse of the coefficient matrix is 
[[-0.01111111 -0.26666667  0.11111111]
 [-0.2         0.2        -0.        ]
 [ 0.08888889  0.13333333  0.11111111]]

The determinant is  -90.0

The rank is  3

The eigenvalues are 
[-5.  3.  6.]
The eigenvectors (rows) are 
[[ 0.81649658  0.40824829 -0.40824829]
 [ 0.53452248 -0.80178373 -0.26726124]
 [ 0.05842062  0.35052374  0.93472998]]

The norm is  8.831760866327848

The condition number is  2.5464725730238915


In [5]:
# create a coefficient matrix using Sympy
import sympy as sym
As = sym.Matrix([[-2, -4, 2], [-2, 1, 2], [4, 2, 5]])
#As = sym.Matrix([[1, 0, 0], [0, 2, 0], [0, 0, 3]])

print('The coefficient matrix is ')
print(As)

# calculate the inverse of the coefficient matrix
As_inv = As.inv()
print('The inverse of the coefficient matrix is ')
print(As_inv)

# calculate the solution vector by multiplying the inverse with the constant vector
xs = As_inv * sym.Matrix([5, -3, 4])

# print the solution
print('The solution vector is ')
print(xs)


The coefficient matrix is 
Matrix([[-2, -4, 2], [-2, 1, 2], [4, 2, 5]])
The inverse of the coefficient matrix is 
Matrix([[-1/90, -4/15, 1/9], [-1/5, 1/5, 0], [4/45, 2/15, 1/9]])
The solution vector is 
Matrix([[107/90], [-8/5], [22/45]])


In [6]:


lam = sym.symbols('lambda')
lambda_matrix = sym.Matrix([[lam, 0, 0], [0, lam, 0], [0, 0, lam]])
print('The lambda matrix is ')
print(lambda_matrix)

The lambda matrix is 
Matrix([[lambda, 0, 0], [0, lambda, 0], [0, 0, lambda]])


In [7]:
eigen_matrix = As - lambda_matrix
print('The eigen matrix is ')
print(eigen_matrix)

The eigen matrix is 
Matrix([[-lambda - 2, -4, 2], [-2, 1 - lambda, 2], [4, 2, 5 - lambda]])


In [8]:
det = eigen_matrix.det()
print('The determinant is ')
print(det)

The determinant is 
-lambda**3 + 4*lambda**2 + 27*lambda - 90


In [9]:
eigenvalues = sym.solve(det)
print('The eigenvalues are ')
print(eigenvalues)

The eigenvalues are 
[-5, 3, 6]


In [10]:
eigenvectors = []
for eigenvalue in eigenvalues:
    print('For eigenvalue ',eigenvalue,' the eigenvectors are ')
    print(eigen_matrix.subs(lam, eigenvalue))
    x = sym.symbols('x')
    y = sym.symbols('y')
    z = sym.symbols('z')
    evec = sym.Matrix([x, y, z])
    print(eigen_matrix.subs(lam, eigenvalue) * evec)
    print(sym.solve((eigen_matrix.subs(lam, eigenvalue) * evec)))
    eigenvectors.append(sym.solve((eigen_matrix.subs(lam, eigenvalue) * evec)))
    print()

For eigenvalue  -5  the eigenvectors are 
Matrix([[3, -4, 2], [-2, 6, 2], [4, 2, 10]])
Matrix([[3*x - 4*y + 2*z], [-2*x + 6*y + 2*z], [4*x + 2*y + 10*z]])
{x: -2*z, y: -z}

For eigenvalue  3  the eigenvectors are 
Matrix([[-5, -4, 2], [-2, -2, 2], [4, 2, 2]])
Matrix([[-5*x - 4*y + 2*z], [-2*x - 2*y + 2*z], [4*x + 2*y + 2*z]])
{x: -2*z, y: 3*z}

For eigenvalue  6  the eigenvectors are 
Matrix([[-8, -4, 2], [-2, -5, 2], [4, 2, -1]])
Matrix([[-8*x - 4*y + 2*z], [-2*x - 5*y + 2*z], [4*x + 2*y - z]])
{x: z/16, y: 3*z/8}


In [11]:
# print the eigenvalues and eigenvectors of the coefficient matrix
eigenvalues_linalg, eigenvectors_linalgT = np.linalg.eig(A)
eigenvectors_linalg = eigenvectors_linalgT.T
print('The eigenvalues are ')
print(eigenvalues_linalg)
print('The eigenvectors (rows) are ')
print(eigenvectors_linalg)
print()

The eigenvalues are 
[-5.  3.  6.]
The eigenvectors (rows) are 
[[ 0.81649658  0.40824829 -0.40824829]
 [ 0.53452248 -0.80178373 -0.26726124]
 [ 0.05842062  0.35052374  0.93472998]]


In [12]:
print(eigenvalues)
print(eigenvectors)

[-5, 3, 6]
[{x: -2*z, y: -z}, {x: -2*z, y: 3*z}, {x: z/16, y: 3*z/8}]


In [13]:
# check the eigenvalues and eigenvectors
for i in range(len(eigenvalues_linalg)):
    print('For eigenvalue ',eigenvalues_linalg[i],' matrix to be multiplied is ')
    print(A-eigenvalues_linalg[i]*np.identity(3))
    print('The eigenvector is ')
    print(eigenvectors_linalg[i])
    result = np.dot(A-eigenvalues_linalg[i]*np.identity(3),eigenvectors_linalg[i])
    print('The result of the matrix multiplication is ')
    print(result)
    sum_vals = 0.0
    for j in range(len(result)):
        sum_vals += result[j]
    print('The sum of the elements of the result is ')
    print(sum_vals)
    print()

For eigenvalue  -5.000000000000005  matrix to be multiplied is 
[[ 3. -4.  2.]
 [-2.  6.  2.]
 [ 4.  2. 10.]]
The eigenvector is 
[ 0.81649658  0.40824829 -0.40824829]
The result of the matrix multiplication is 
[ 4.55191440e-15  1.44328993e-15 -3.55271368e-15]
The sum of the elements of the result is 
2.4424906541753444e-15

For eigenvalue  3.0  matrix to be multiplied is 
[[-5. -4.  2.]
 [-2. -2.  2.]
 [ 4.  2.  2.]]
The eigenvector is 
[ 0.53452248 -0.80178373 -0.26726124]
The result of the matrix multiplication is 
[-1.33226763e-15 -1.33226763e-15 -1.11022302e-15]
The sum of the elements of the result is 
-3.774758283725532e-15

For eigenvalue  6.0  matrix to be multiplied is 
[[-8. -4.  2.]
 [-2. -5.  2.]
 [ 4.  2. -1.]]
The eigenvector is 
[0.05842062 0.35052374 0.93472998]
The result of the matrix multiplication is 
[-4.44089210e-16  1.55431223e-15  2.22044605e-16]
The sum of the elements of the result is 
1.3322676295501878e-15


In [14]:
print(A)

[[-2 -4  2]
 [-2  1  2]
 [ 4  2  5]]


In [15]:
print("Eigenvalues")
print(eigenvalues_linalg)
print("Eigenvector matrix with eigenvectors as columns")
print(eigenvectors_linalgT)
S = eigenvectors_linalgT

Eigenvalues
[-5.  3.  6.]
Eigenvector matrix with eigenvectors as columns
[[ 0.81649658  0.53452248  0.05842062]
 [ 0.40824829 -0.80178373  0.35052374]
 [-0.40824829 -0.26726124  0.93472998]]


In [16]:
Sinv = np.linalg.inv(S)
print("Inverse of eigenvector matrix with eigenvectors as columns")
print(Sinv)

Inverse of eigenvector matrix with eigenvectors as columns
[[ 7.79383100e-01  6.12372436e-01 -2.78351107e-01]
 [ 6.23609564e-01 -9.35414347e-01  3.11804782e-01]
 [ 5.18704326e-01 -5.38684062e-16  1.03740865e+00]]


In [17]:
Lambda = np.diag(eigenvalues_linalg)
print("Eigenvalue matrix (diagonal)")
print(Lambda)

Lambda_Theory = np.dot(Sinv, np.dot(A,S))

print("Eigenvalue matrix (diagonal) calculated from Sinv, A, S")
print(Lambda_Theory)


Eigenvalue matrix (diagonal)
[[-5.  0.  0.]
 [ 0.  3.  0.]
 [ 0.  0.  6.]]
Eigenvalue matrix (diagonal) calculated from Sinv, A, S
[[-5.00000000e+00 -2.16543259e-15  5.58796001e-16]
 [ 8.79920962e-16  3.00000000e+00 -1.88346540e-15]
 [-1.21931946e-15 -2.06707649e-15  6.00000000e+00]]


In [18]:
A_Theory = np.dot(S, np.dot(Lambda, Sinv))
print("A calculated from S, Lambda, Sinv")
print(A_Theory)

A calculated from S, Lambda, Sinv
[[-2. -4.  2.]
 [-2.  1.  2.]
 [ 4.  2.  5.]]
